//! cc-i18n: multilingual message support based on rust-i18n.
//!
//! The original Go implementation (`internal/i18n`) used go-i18n + `{{.Field}}` templates,
//! but this port uses the rust-i18n crate. Locale files (`locales/*.yml`) are converted
//! from go-i18n YAML to rust-i18n format (`%{Field}` interpolation); message content is
//! identical 1:1.
//!
//! To allow use from multiple crates in the workspace, instead of rust-i18n's `t!` macro
//! (which expands to `crate::_rust_i18n_t!` and binds to the defining crate), we expose
//! a runtime function [`translate`] that wraps the `_rust_i18n_translate` generated by
//! `i18n!`, along with our own [`t!`](crate::t) macro. Call sites retain a form nearly
//! identical to Go's `i18n.T(key, fields)`.

rust_i18n::i18n!("locales", fallback = "en");

/// Initializes the locale to a supported language. If the string is empty, auto-detects from environment variables.
/// Corresponds to Go `i18n.Init`.
pub fn init(lang: &str) {
    let l = if lang.is_empty() {
        detect_locale()
    } else {
        normalize(lang)
    };
    rust_i18n::set_locale(&l);
}

/// Returns the current locale code (`ko`/`en`/`ja`/`zh`).
pub fn current_locale() -> String {
    rust_i18n::locale().to_string()
}

/// Explicitly sets the locale.
pub fn set_locale(lang: &str) {
    rust_i18n::set_locale(&normalize(lang));
}

/// Returns the translated string for `key` and interpolates `%{Field}` placeholders with `args`.
/// Returns `[key]` when the translation key is not found (same behavior as Go on failure).
pub fn translate(key: &str, args: &[(&str, String)]) -> String {
    let locale = current_locale();
    // `try_translate` looks up current locale → fallback("en") in order, returning None
    // if not found in either. Go's T() returns `[msgID]` on failure, so we do the same.
    match _rust_i18n_try_translate(&locale, key) {
        Some(raw) => interpolate(raw.as_ref(), args),
        None => format!("[{key}]"),
    }
}

/// Replaces `%{Field}` placeholders with values from `args`. Unmatched placeholders are
/// left as-is in the original text.
fn interpolate(template: &str, args: &[(&str, String)]) -> String {
    if !template.contains("%{") {
        return template.to_string();
    }
    let mut out = String::with_capacity(template.len());
    let bytes = template.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 1 < bytes.len() && bytes[i + 1] == b'{' {
            if let Some(end_rel) = template[i + 2..].find('}') {
                let name = &template[i + 2..i + 2 + end_rel];
                if let Some((_, val)) = args.iter().find(|(k, _)| *k == name) {
                    out.push_str(val);
                } else {
                    out.push_str(&template[i..i + 2 + end_rel + 1]);
                }
                i = i + 2 + end_rel + 1;
                continue;
            }
        }
        // Copy one character safely in UTF-8.
        let ch_len = utf8_char_len(bytes[i]);
        out.push_str(&template[i..i + ch_len]);
        i += ch_len;
    }
    out
}

fn utf8_char_len(b: u8) -> usize {
    if b < 0x80 {
        1
    } else if b >> 5 == 0b110 {
        2
    } else if b >> 4 == 0b1110 {
        3
    } else if b >> 3 == 0b11110 {
        4
    } else {
        1
    }
}

/// Detects the language code from environment variables.
/// Priority: `GIT_WARDEN_LANG` > `LC_ALL` > `LC_MESSAGES` > `LANG`.
/// Falls back to `en` on detection failure. Corresponds to Go `i18n.DetectLocale`.
pub fn detect_locale() -> String {
    for env in ["GIT_WARDEN_LANG", "LC_ALL", "LC_MESSAGES", "LANG"] {
        if let Ok(val) = std::env::var(env) {
            if !val.is_empty() {
                let tag = parse_locale(&val);
                if !tag.is_empty() {
                    return tag;
                }
            }
        }
    }
    "en".to_string()
}

/// Extracts a language code from a `ko_KR.UTF-8`-style string. Corresponds to Go `parseLocale`.
fn parse_locale(val: &str) -> String {
    let mut v = val.to_lowercase();
    if let Some(idx) = v.find(['_', '.']) {
        if idx > 0 {
            v = v[..idx].to_string();
        }
    }
    match v.as_str() {
        "ko" => "ko",
        "ja" => "ja",
        "zh" => "zh",
        "en" | "c" | "posix" => "en",
        _ => "en",
    }
    .to_string()
}

/// Normalizes an explicit language input to a supported locale code.
fn normalize(lang: &str) -> String {
    parse_locale(lang)
}

/// Macro corresponding to go-i18n's `i18n.T(key, map)`.
///
/// ```ignore
/// cc_i18n::t!("diff.binary_file_error", Path = path);
/// cc_i18n::t!("step.summary", Count = n, Checks = checks);
/// cc_i18n::t!("cmd.version.label");
/// ```
#[macro_export]
macro_rules! t {
    ($key:expr) => {
        $crate::translate($key, &[])
    };
    ($key:expr, $($name:ident = $val:expr),+ $(,)?) => {
        $crate::translate($key, &[$((stringify!($name), ::std::string::ToString::to_string(&$val))),+])
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    // set_locale changes process-global state, so locale-dependent tests must be serialized.
    static LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn translate_with_fields() {
        let _g = LOCK.lock().unwrap();
        set_locale("ko");
        let s = t!("diff.binary_file_error", Path = "a.out");
        assert!(s.starts_with("a.out: "), "got: {s}");
        assert!(!s.contains("%{"));
    }

    #[test]
    fn fallback_to_en_for_missing_locale_key() {
        let _g = LOCK.lock().unwrap();
        set_locale("en");
        let s = t!("diff.kind_comment");
        assert_eq!(s, "comment");
    }

    #[test]
    fn missing_key_returns_bracketed() {
        let _g = LOCK.lock().unwrap();
        set_locale("ko");
        assert_eq!(t!("no.such.key"), "[no.such.key]");
    }

    #[test]
    fn multiline_value_preserves_newlines() {
        let _g = LOCK.lock().unwrap();
        set_locale("ko");
        // migrate.saved has the form "\n%{Path} migration complete."
        let s = t!("migrate.saved", Path = "cfg.yml");
        assert!(s.starts_with('\n'), "got: {s:?}");
        assert!(s.contains("cfg.yml"));
    }

    #[test]
    fn detect_locale_parses_lang_env() {
        assert_eq!(parse_locale("ko_KR.UTF-8"), "ko");
        assert_eq!(parse_locale("en_US.UTF-8"), "en");
        assert_eq!(parse_locale("C"), "en");
        assert_eq!(parse_locale("ja"), "ja");
        assert_eq!(parse_locale("fr_FR"), "en");
    }
}
