name: CI

on:
  push:
    branches: ["main"]
    tags-ignore: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt --all --check

      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Build
        run: cargo build --workspace

      - name: Test
        run: cargo test --workspace

  msrv:
    name: MSRV (1.88)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain (MSRV)
        uses: dtolnay/rust-toolchain@1.88

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: msrv

      - name: Build
        run: cargo build --workspace

      - name: Test
        run: cargo test --workspace
